# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

.PHONY: bootstrap-storage check-bootstrap-storage
bootstrap-storage: ## Creates and verifies the persistent LVMS loop device (may reboot the SNO node)
	@./scripts/bootstrap-local-storage.sh

check-bootstrap-storage: ## Verifies the storage prerequisite is satisfied (read-only)
	@./scripts/bootstrap-local-storage.sh check

# Defining prerequisites before including the common target keeps this ordering
# even when make is invoked with -j.
pattern-install: check-bootstrap-storage

.PHONY: validate-observability
validate-observability: ## Renders and validates the observability configuration chart and its shell tests
	@tests/validate-pattern-config.sh
	@tests/test-observability-dashboards.sh
	@tests/test-observability-alerts.sh
	@tests/test-observability-configurability.sh
	@tests/test-observability-rbac.sh
	@tests/test-observability-override.sh
	@tests/test-cluster-summary-dashboard.sh


.PHONY: validate-openshell
validate-openshell: ## Renders and validates the OpenShell platform charts and their shell tests
	@tests/test-openshell-values.sh
	@tests/test-openshell-secrets.sh
	@tests/test-openshell-quota.sh
	@tests/test-openshell-render.sh
	@tests/test-openshell-ordering.sh
	@tests/test-openshell-pins.sh
	@tests/test-openshell-ztwim.sh


include Makefile-common
