# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

.PHONY: bootstrap-storage check-bootstrap-storage
bootstrap-storage: ## Creates and verifies the persistent LVMS loop device (may reboot the SNO node)
	@./scripts/bootstrap-local-storage.sh

check-bootstrap-storage: ## Verifies the storage prerequisite is satisfied (read-only)
	@./scripts/bootstrap-local-storage.sh check

# Defining prerequisites before including the common target keeps this ordering
# even when make is invoked with -j.
pattern-install: check-bootstrap-storage

.PHONY: validate-observability
validate-observability: ## Renders and validates the observability configuration chart and its shell tests
	@tests/validate-pattern-config.sh
	@tests/test-observability-dashboards.sh
	@tests/test-observability-alerts.sh
	@tests/test-observability-configurability.sh
	@tests/test-observability-rbac.sh
	@tests/test-observability-override.sh
	@tests/test-cluster-summary-dashboard.sh


.PHONY: validate-openshell
validate-openshell: ## Renders and validates the OpenShell platform charts and their shell tests
	@tests/test-openshell-values.sh
	@tests/test-openshell-secrets.sh
	@tests/test-openshell-quota.sh
	@tests/test-openshell-render.sh
	@tests/test-openshell-ordering.sh
	@tests/test-openshell-pins.sh
	@tests/test-openshell-ztwim.sh
	@tests/test-keycloak-realm.sh
	@tests/test-external-refs.sh

.PHONY: validate-openshell-live
validate-openshell-live: check-openshell-cli ## Live-cluster auth smoke test (Keycloak OIDC + gateway); requires oc + DNS access
	@tests/test-openshell-auth-smoke.sh

.PHONY: validate-openshell-demo
validate-openshell-demo: ## Scripted V-DEMO smoke (opencode-in-sandbox vs matilda); skips when cluster unreachable
	@if ! oc get --raw /healthz >/dev/null 2>&1; then echo "skip: cluster unreachable (validate-openshell-demo)"; exit 0; fi; \
	if ! openshell status -g k8s >/dev/null 2>&1; then echo "skip: gateway auth missing (login: OPENSHELL_NO_BROWSER=1 openshell gateway login k8s)"; exit 0; fi; \
	DEMO_PROMPT="Reply with exactly: OPENSHELL_VDEMO_OK" deploy/openshell/demo/run-demo.sh --smoke

.PHONY: check-openshell-cli
check-openshell-cli: ## Asserts the installed openshell CLI matches the chart-pinned server version
	@tests/check-openshell-cli.sh

.PHONY: install-openshell-cli
install-openshell-cli: ## Installs the openshell CLI at the chart-pinned version (brew preferred)
	@ver=$$(python3 -c "import yaml;p=yaml.safe_load(open('values-prod.yaml'))['clusterGroup'];print(str(p['applications']['openshell']['chartVersion']))"); \
	if command -v brew >/dev/null 2>&1 && [ "$$(brew info openshell --json=v2 2>/dev/null | python3 -c 'import sys,json;d=json.load(sys.stdin);print(d["casks"][0]["versions"]["stable"] if d.get("casks") else d["formulae"][0]["versions"]["stable"])' 2>/dev/null)" = "$$ver" ]; then \
	  brew install openshell; \
	else \
	  echo "brew formula does not carry $$ver; using upstream installer into ~/.local/bin"; \
	  OPENSHELL_VERSION=v$$ver OPENSHELL_INSTALL_DIR="$$HOME/.local/bin" curl -fsSL https://github.com/NVIDIA/OpenShell/releases/download/v$$ver/install.sh | sh; \
	fi; \
	tests/check-openshell-cli.sh


include Makefile-common
