clusterGroup:
  name: prod
  namespaces:
    minilab:
    vault:
    external-secrets:
    
  subscriptions: {}
  applications:
    vault:
      name: vault
      namespace: vault
      project: default
      chart: hashicorp-vault
      chartVersion: 0.1.*
    secrets-operator:
      name: openshift-external-secrets
      namespace: external-secrets
      project: external-secrets
      chart: openshift-external-secrets
      chartVersion: 0.0.*
  projects: 
  - default
  sharedValueFiles:[]
  # imperative:
