{{- if .Values.global.observability.enabled }}
{{- $obs := .Values.global.observability }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: {{ .Values.uiPlugin.name }}
  namespace: {{ $obs.cooNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: Monitoring
  monitoring:
    perses:
      enabled: true
{{- end }}